### ISSUE TITLE
date_closed & open_date

### ISSUE THREAD

**Issue by mberg** [facilityregistry/fred-api#12]
Do we want to support the idea of a date_closed and open_date as core properties?

I believe Bob said this is an important component of DHIS2

**Comment by rowenaluk** [comment]
this raises the question of what 'closed' and 'open' actually means, which i'm sure could be a point of contention.

since we already have agreement on 'active' as a core field, I'd be more in favour of something like 'date_active' and 'date_inactive'.

that said, this doesn't strike me as a core attribute. Bob, maybe you could elaborate on how it's been needed in practice?

**Comment by mberg** [comment]
You're right it's probably not a core property and probably needs to be
implementation specific.

**Comment by mortenoh** [comment]
I think the case for having it in DHIS 2, was that we want to disallow data entry before the opening date. Which might be different from created date. I'm fine with keeping it out of core for 1.0, maybe we can raise the issue for 1.1.

**Comment by mberg** [comment]
Moving to discussion for 1.1

**Comment by mberg** [comment]
Not a core property.  Should be handled by extended property.
