### ISSUE TITLE
Single format

### ISSUE THREAD

**Issue by bobjolliffe** [facilityregistry/fred-api#2]
The facilities registry data is currently to be returned in both XML and JSON format. I suggest that we pick one.

Requiring support for a single format makes it easier to build new API implementations. Supporting two formats opens the possibility for subtle differences in specification or implementation.

The disadvantage of this proposal is that consumers of the API who prefer the unsupported format will need to work with the one that is, but I'm not aware of any programming environment we would be totally excluding if we went with a single format.

My personal preference is JSON, as to me it is a simpler data exchange format, though I think XML-only would be better than both.

**Comment by rowenaluk** [comment]
+1

**Comment by ctford** [comment]
As I say, I prefer JSON, but if we do go with XML, could we please avoid using something like XML Schema that will cause any addition of a field to be a breaking change?

**Comment by bobjolliffe** [comment]
The use of a schema doesn't necessarily imply that the addition of a field
will cause a breaking change.  The schema can be quite permissive.  For
example, anywhere where we have attributes we have the provision
for xs:anyAttribute, ie there can be more attributes which are not
specified in this version of the spec.

The same is almost true of additional extension elements, with the further
limitation that any elements can appear (_after_ the prescribed ones) but
they must be in a separate namespace.  So for example a resource mapper
instance in Rwanda may produce any number of additional elements to meet
Rwandan requirements but they would be in a Rwanda specific namespace.

There could be a case for dropping this foreign namespace requirement, in
which case the facility registry entity would consist of a number of
prescribed fields + anything else.  I am in two minds about the merits of
this but am happy to consider what others might think.

**Comment by ctford** [comment]
My feeling is that in order to make XML Schema truly exensible, you need to pepper "any"s literally everywhere, which reduces the schema's effectiveness as documentation. My worry is that consumers will use an XML Schema that's not fully extensible with something like JAXB and produce client code that will break in the presence of new fields or attributes.

I'm also not a big fan of using imported namespaces to mix in new elements as I think it gets a little complex. I'm more a fan of the prescribed fields + anything else approach, though if we quarantined the "anything else" to the properties key, then we can add new prescribed fields without risking clashing with any custom ones.

**Comment by edjez** [comment]
I strongly think we should design one 1.0 or 1.1 endpoint first, doing a good job in a specific format with all the issues and constraints and conventions of that format. And then deal with the other format.

That said, I prefer that we work first on a JSON endpoint first and then XML.

**Comment by mberg** [comment]
Proposed using XML for the formal spec but do the initial implementation in JSON and do it well.

The formal documentation (contracts) will be in XML style.
