### ISSUE TITLE
versioning proposal

### ISSUE THREAD

**Issue by bobjolliffe** [facilityregistry/fred-api#3]
Comment submitted by Chris Ford on mailing list 2012/11/14

I was thinking about the versioning discussion we were having earlier, and I'd like to suggest a compromise that would allow us to avoid the complexity of content negotiation, but still keep our URLs fairly stable. The trick is to mint URLs only on breaking changes.

The strategy can be summed up in these rules:
Clients MUST ignore fields they do not recognise.
Content-Type identifiers MUST include a version number with major and minor versions (e.g. application/fred.facility.v1-5+json, application/fred.collection.v2-0+json) and MUST be backwards compatible with other versions with the same major and lower minor version numbers.
Servers MUST serve a Content-Type response header along with successful (2xx) responses.
Servers MAY increment the minor version number of content they serve at a particular URL.
Servers MUST use a new URL if they increment the major version number of content.
If these rules are obeyed, we can easily make expanding change to the API without content negotiation or breaking existing clients. Backwards-incompatible changes will require a new URL-space and will cause existing links to point to old API versions, but this will be comparatively infrequent (and perhaps will never happen). Clients who encounter older versions of the service than they expect will be able to use the Content-Type to work out which elements not to rely on.

A simple way for servers to implement a new URL-space per major version would be to include "v1", "v2" etc in all URLs, but this should not be part of the published contract, otherwise clients would rely on details of URL structure.

**Comment by ctford** [comment]
From [Rowena](https://github.com/rowenaluk):

Hi Chris, thanks for writing up your thoughts.

I propose that we remove this line: Servers MUST use a new URL if they increment the major version number of content. If it's a backwards-compatible major version increment, we should not require clients to change their URLs.

That said, while I like much of the thinking you've put into this, I'd still prefer to keep API information in the URL rather than the HTTP headers, simply for ease of implementation for developers coming from a variety of backgrounds. Clients will need to rely on something, and that will be easiest/safest to find in the URL.

**Comment by ctford** [comment]
From [Bob](https://github.com/bobjolliffe):

Hi Rowena

I think this could be tidied up a bit (I just copied and pasted from Chris' email) but I think the intent is that there would not be a backwards-compatible major version increment. A major version increment would imply some breaking changes.

The net effect being that clients should always be able to rely on a particular URL. They may not be able to make sense of all the fields but if they ignore what they can't understand they will be fine.

**Comment by ctford** [comment]
From [Chris](https://github.com/ctford):

Yes, Bob's explanation fits what I was thinking. Because we want to be conservative on when we move URLs, I see a major revision bump and backwards incompatibility as always going together.

**Comment by ctford** [comment]
From [Chris](https://github.com/ctford):

Here is my motivating use case for not encoding version information in the URL (unless we really have to e.g. a breaking change).

Consider the case where we have other services that want to link to a facilities registry, which I believe is likely in Uganda. What URLs should they use?

```
http://example.org/v1.0/facilities/123
http://example.org/v1.1/facilities/123
http://example.org/v1.2/facilities/123
```

The problem is, there's no way for the linking service to know what version its clients can consume. Indeed, it may have multiple clients that all want different versions. If they get it wrong, then their consumers may break.

If we only change URLs for backwards-incompatible changes, then we keep the URLs as stable as possible for the benefit of other services that want to interoperate with us. If we change the URLs whenever we make any change, we become a less open system.

When we have interconnected services, the party that needs to work with the URLs is the service that links to our API, not the direct consumers of our API.

**Comment by rowenaluk** [comment]
What if we added

Servers MUST continue to serve URLs for versions that they continue to support. 

So, a server might expose all of: 
http://example.org/v1.0/facilities/123
http://example.org/v1.1/facilities/123
http://example.org/v1.2/facilities/123

And then different clients could link to whichever URL they prefer. The only time a server kills one of these URLs is when it stops supporting that format. It doesn't have to kill 1.0 when it also starts supporting 1.1.

**Comment by ctford** [comment]
That still concerns me a little from the point of view of a linking service. Certainly it's a good thing that we don't kill old URLs, but another service will still be linking to old versions and clients of that other service can't take advantage of new features.

What's the main motivation for including major and minor versions in the URL? Transparency and usability of the API for programmers writing clients?

**Comment by rowenaluk** [comment]
A linking service could keep a catalogue of what versions are supported and expose the appropriate URLs?

Yeah, this is about transparency and usability. I'm also not a huge fan of constraining ourselves to saying that "we can only increment major version numbers when the change is not backwards compatible". This feels like it will be confusing, and inconsistent with common understandings of what 'major versions' mean.

**Comment by ctford** [comment]
There is some precedent for equating major version bumping and backwards incompatibility e.g. [semantic versioning](http://semver.org/). But obviously the fact that we're discussing this proves your point that it's not something that's universally agreed. :-p

I think that having a list of the links to various versions of the API is a great idea, regardless of what conditions we have new URLs. Did you mean in documentation or a machine-readable service? The latter is cool, but feels a bit like content-negotiation all over again if we expect consumers to automatically select versions they're interested in.

**Comment by edjez** [comment]
We recommended semver some time ago and it's pretty good for norming the use of version numbers. 
How those are used in REST entities and URLs is the more complicated question (eg major version only? minor too? only headers?).

**Comment by mberg** [comment]
Agree to:

Include to also include the minor version in the header response.

We use semantic versioning with major versions for backwards incompatibility.  

You need to expose the major version in the URL (define a more normative approach in future versions potentially).
